"""add company and default_payment_link to users

Revision ID: 22f32f933e9d
Revises: 5a3d7e8f9c01
Create Date: 2026-05-25 09:41:33.394101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f32f933e9d'
down_revision = '5a3d7e8f9c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('default_payment_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_payment_link')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
