"""Add blocked flag to users

Revision ID: 502bb0fe4904
Revises: 4f5f513039ce
Create Date: 2026-05-23 10:49:56.005857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502bb0fe4904'
down_revision = '4f5f513039ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
